### ISSUE TITLE
Replace contents of languages.rb with data from YAML files

### ISSUE THREAD

**Issue by mojca** [hyphenation/tex-hyphen#12]
We won't be able to put everything in those YAML files (for example, we would still want to group languages outside of pattern files or provide some metadata that's only relevant for packaging), but versions, licences etc. should be kept up to date and consistent, no reason to duplicate the information.

**Comment by reutenauer** [comment]
Done!  See [commit 7a314a1](https://github.com/hyphenation/tex-hyphen/commit/7a314a1)
