### ISSUE TITLE
Update Church Slavonic patterns

### ISSUE THREAD

**Issue by mojca** [hyphenation/tex-hyphen#3]
Update patterns from https://github.com/slavonic/cu-tex/blob/master/hyphenation/hyph-cu.tex

@pgmmpk

**Comment by pgmmpk** [comment]
Here is my attempt to do the necessary changes:

https://github.com/hyphenation/tex-hyphen/pull/4

**Comment by pgmmpk** [comment]
Hi, any update on this issue? Thanks!

**Comment by reutenauer** [comment]
I can do it some time in the coming week.

Arthur

**Comment by mojca** [comment]
This has been fixed by #4, so I'm closing this issue.
